- hosts: nodes
  tasks:
  - stat: path=/sys/firmware/efi/efivars/
    register: grub_efi
  - debug: var=grub_efi
  
  - name: Change GRUB config
    lineinfile:
      backup: yes
      backrefs: yes
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="(.*)$'
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 \1 '
  
  - name: grub2-mkconfig EFI
    command: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
    when: grub_efi.stat.exists == True

  - name: grub2-mkconfig MBR
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: grub_efi.stat.exists == False