- hosts: nodes
  tasks:
  - name: Install httpd
    yum: 
      pkg: httpd 
      state: latest

  - name:  Start apache
    service: 
      name: httpd 
      state: started
      enabled: yes

  - name: Check status of httpd
    service_facts:
    register: service_state
  - debug:
      var: service_state.ansible_facts.services["httpd.service"].state

  - name: Add index.html
    copy:
      content: "Welcome to my website"
      dest: /var/www/html/index.html
  
  - name: Open ports in firewalld
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp
      
  - name: restart firewalld
    service: 
      name: firewalld 
      state: restarted

  - name: Disable NetworkManager service
    service: 
      name: NetworkManager
      state: stopped
      
  - stat: path=/sys/firmware/efi/efivars/
    register: grub_efi
  - debug: var=grub_efi
  
  - name: Change GRUB config
    lineinfile:
      backup: yes
      backrefs: yes
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0 biosdevname=0\2'

  
  - name: grub2-mkconfig EFI
    command: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
    when: grub_efi.stat.exists == True

  - name: grub2-mkconfig MBR
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: grub_efi.stat.exists == False