- hosts: nodes
  tasks:
  - name: Install httpd
    yum: pkg=httpd state=latest

  - name:  start apache
    service: name=httpd state=started

  - name: Add index.html
    copy:
      content: "Welcome to my website"
      dest: /var/www/html/index.html
  
  - name: permit traffic in default zone for https service
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp
      
  - name: restart firewalld
    service: name=firewalld state=restarted