- hosts: nodes
  tasks:
  - name: Install httpd
    yum: pkg=httpd state=latest

  - name:  start apache
    service: name=httpd state=started

  - name: Check status of alertmanager service
    service_facts:
    register: service_state
  - debug:
      var: service_state.ansible_facts.services["httpd.service"].state

  - name: Add index.html
    copy:
      content: "Welcome to my website"
      dest: /var/www/html/index.html
  
  - name: Open ports in firewalld
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp
      
  - name: restart firewalld
    service: name=firewalld state=restarted