- hosts: nodes
  vars_files:
    vars.yaml 
  tasks:
  - name: Install vsftpd
    yum: 
      name: vsftpd 
      state: latest
  
  - name:  Start service
    service: 
      name: vsftpd 
      state: started
      enabled: yes

  - name: Open ports in firewalld
    firewalld:
      service: ftp
      permanent: yes
      state: enabled

  - name: restart firewalld
    service: 
      name: firewalld 
      state: restarted

  - name: FTP folder permissions
    file:
      path: /var/ftp/pub
      owner: "ftp"
      group: "ftp"
      mode: 0755

  - name: Template to copy vsftpd.conf
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf

  - name: Restart vsftpd
    service: 
      name: vsftpd 
      state: restarted

  - name: Install SELinux requirements
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - python3-libselinux
      - policycoreutils-python-utils
  
  - name: Change SELinux bool
    seboolean:
      name: ftpd_anon_write
      state: yes

  - name: Change SElinux context
    sefcontext:
      target: /var/ftp/pub
      setype: public_content_rw_t
      state: present

  - name: Apply new SELinux file context to filesystem
    command: restorecon -irv /var/ftp/pub